site_name: Test Live Checkout v1.1.0
site_dir: 1.1.0
copyright: 'Copyright &copy; 2019 <a href="https://auroraextensions.com" target="_blank">Aurora Extensions</a>'
theme:
  name: mkdocs
  custom_dir: theme
nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Configuration: configuration.md
  - Examples:
    - 'Guest Checkout':
      - 'Authorize.net': 'examples/guest-checkout/authorizenet.md'
      - 'Braintree': 'examples/guest-checkout/braintree.md'
  - Manuals: 'manuals/index.md'
extra_css:
  - css/extra.css
google_analytics: ['UA-113897119-2', 'docs.auroraextensions.com']
