site_name: Test Live Checkout
site_dir: 1.0.1
theme: mkdocs
pages:
  - Home: index.md
  - Quick Start: quickstart.md
  - Configuration: configuration.md
  - Examples:
    - 'Guest Checkout': 'examples/guest-checkout.md'
extra_css:
  - css/extra.css
google_analytics: ['UA-113897119-2', 'nickolasburr.github.io']
