site_name: Sample Data Extensions
site_dir: index
copyright: 'Copyright &copy; 2019 <a href="https://auroraextensions.com" target="_blank">Aurora Extensions</a>'
theme: mkdocs
nav:
  - Home: index.md
  - Extensions:
    - 'Simple Returns': 'simplereturns/index.md'
extra_css:
  - css/extra.css
google_analytics: ['UA-113897119-2', 'docs.auroraextensions.com']
