site_name: Test Live Checkout v1.1.0
site_dir: 1.1.0
theme: mkdocs
pages:
  - Home: index.md
  - Quick Start: quickstart.md
  - About: about.md
  - Configuration: configuration.md
  - Examples:
    - 'Guest Checkout':
      - 'Authorize.net': 'examples/guest-checkout/authorizenet.md'
      - 'Braintree': 'examples/guest-checkout/braintree.md'
  - Manuals: 'manuals/index.md'
extra_css:
  - css/extra.css
google_analytics: ['UA-113897119-2', 'nickolasburr.github.io']
