site_name: Google Cloud Pub/Sub Event Analytics v1.0.1
site_dir: 1.0.1
theme: mkdocs
nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Manuals: manuals/index.md
extra_css:
  - css/extra.css
google_analytics: ['UA-113897119-2', 'docs.nickolasburr.com']
