site_name: Google Cloud Pub/Sub Event Analytics v1.0.1
site_dir: 1.0.1
copyright: 'Copyright &copy; 2019 <a href="https://auroraextensions.com" target="_blank">Aurora Extensions</a>'
theme: mkdocs
nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Manuals: manuals/index.md
extra_css:
  - css/extra.css
google_analytics: ['UA-113897119-2', 'docs.auroraextensions.com']
