site_name: Tokenize Product Downloads v1.0.0
site_dir: 1.0.0
copyright: 'Copyright &copy; 2019 <a href="https://auroraextensions.com" target="_blank">Aurora Extensions</a>'
theme: mkdocs
pages:
  - Home: index.md
  - Configuration: configuration.md
  - Manuals: manuals/index.md
extra_css:
  - css/extra.css
google_analytics: ['UA-113897119-2', 'docs.auroraextensions.com']
