site_name: Cron Cloud Functions v1.0.0
site_dir: 1.0.0
theme: mkdocs
pages:
  - Home: index.md
  - Installation: installation.md
  - Examples: examples/index.md
    - 'Visitor Log Clean': examples/visitor_log_clean.md
extra_css:
  - css/extra.css
google_analytics: ['UA-113897119-2', 'docs.nickolasburr.com']
