site_name: Google Cloud Pub/Sub Inventory Management v1.0.1
site_dir: 1.0.0
theme: mkdocs
nav:
  - Home: index.md
extra_css:
  - css/extra.css
google_analytics: ['UA-113897119-2', 'docs.auroraextensions.com']
